### ISSUE TITLE
"The server did not send any content back. Likely due to an internal server error" on a fresh install

### ISSUE THREAD

**Issue by ecw2-4** [GroundApps/ShoppingList#14]
I'm getting "The server did not send any content back. Likely due to an internal server error"

The weird thing is: I press "retry", and while the connection is being retried, I can quicly add a "new entry". That item is then correctly added to the "shoppinglist.sqlite" file. But I still get above error message.

**Comment by J-8** [comment]
Did you try anything else? I (or anyone else) have to investigate. The problem is because I was very careless with the error messages we have #6

**Comment by Schm1tz1** [comment]
Same problem here. I tried with a simple SQLITE database and even removed the authKey-stuff, but the app does not seem to connect correctly, the database file is not created. Is there any kind of error log for the app ? PHP-Error log is empty.

**Comment by J-8** [comment]
I have time tomorrow to fix a couple of things and hopefully push a first update. That will definitely include better error handling!

**Comment by Schm1tz1** [comment]
Update: The problem seems to be caused by some HTML and JavaScript code which is automatically added by the free hosting service I am using (byethost). This causes the JSON parser to fail. Maybe one can strip HTML and code tags before data is passed to the JSON parser. I will investigate...

Here are the important lines from the error output:
08-25 12:26:49.284  26814-26814/org.janb.shoppinglist D/JSON﹕ function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("835dec7ff8a9f595aabe53224b241868");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";location.href="http://myserver?ckattempt=1";This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support
08-25 12:26:49.284  26814-26814/org.janb.shoppinglist W/System.err﹕ org.json.JSONException: Value function of type java.lang.String cannot be converted to JSONArray
(...)
08-25 12:26:49.285  26814-26814/org.janb.shoppinglist I/SHOPPING LIST﹕ No data received from server

**Comment by J-8** [comment]
Okay, thanks for investigating! Could you post the whole source of the page to pastebin or something, so I can try to find a solution?

**Comment by Schm1tz1** [comment]
Here's the output before parsing: https://gist.github.com/31a14ba2a83b5ac21cd7.git
This seems to be some kind of injected 'standard code' from the hoster which redirects you via JS to the page you are originally trying to access. You can strip all the HTML and JS code with Regexp and "Http.fromHtml()" but this only leaves you with an empty string for the JSON parser. Maybe I have to switch to some different server, this seems to be an issue of the hosting service. Such redirects are not always wanted and could be a potential security issue for an app. No improvement using URLConnection.setInstanceFollowRedirects(true), same output.

**Comment by Schm1tz1** [comment]
Sorry, link broken somehow. 
https://gist.github.com/Schm1tz1/31a14ba2a83b5ac21cd7

**Comment by J-8** [comment]
Maybe a change of hosting provider does present the better course of action here. I do not think it is possible or feasible to check for individual redirects. I can really recommend self-hosting;)

**Comment by J-8** [comment]
The new error reporting will help out quicker for that type of error.
