### ISSUE TITLE
More flexible Host configurations

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#16]
presently, I must put https://MYHOST.com/sholi/api.php exactly. I cannot omit the https:// and I cannot omit the api.php. The sub-text of the item says "the _location_ of api.php", which makes me think that I should put the folder in which api.php resides, not to put the exact path in.

It should not care whether https://, http://, or whatever is preceding the address, and it should be clearer as to whether it expects an exact path or not.

**Comment by J-8** [comment]
There is no differentiation between http and ssl. However, you should really use https. But I guess, it is because you don't have a commercial certificate.
I will try to include a way to use self-signed certificates.
About the location: I will add DirectoryIndex api.php to the .htaccess so the address we need can omit the api.php --> example.com/sholi/

**Comment by ghost** [comment]
No, no, what I meant was that I have to manually type it in to the address field. It should be agnostic so it would work with http://MYHOST.com/sholi/api.php or just MYHOST.com/sholi/api.php. Just like how we don't have to type http://google.com every time :)

By all means, don't allow self-signed certs.

**Comment by J-8** [comment]
Ah, get it now!
You are absolutely right.

Well, about self-signed, the is a great library which allows adding a cert to the trusted keystore for just that app. Accepting all certs without check is of course out of the question:D

**Comment by J-8** [comment]
Done :)
