### ISSUE TITLE
The response did not make sense: []

### ISSUE THREAD

**Issue by jessarcher** [GroundApps/ShoppingList#38]
Firstly I just wanted to say that it's fantastic to see a FOSS shopping list app for Android with a self-hosted syncing solution!

My issue is that when I upgraded to version 1.1 of the app, I received an error when trying to display the list of items: "The response did not make sense: " followed by a JSON string of the items in the database. I have since upgraded to a fresh install of the latest backend (version 0.3 / commit 6729fbc) and also uninstalled and then reinstalled and reconfigured the app, but I am still receiving the error, although now with an empty JSON string due to the fresh install of the backend: "The response did not make sense: []"

When accessing the API directly and passing function=listall along with the appropriate auth key, I can confirm that it is just returning `[]` but I assume this is expected behavior from a backend with a fresh database (SQLite FWIW).

I am a PHP developer and would love to help out with the backend if I can, but this seems like it might be an issue with the app. Please let me know if there is any further information that might be helpful or if I can provide assistance in any way.

**Comment by J-8** [comment]
Hey! Thanks for your feedback and offer to help out! Maybe you could check the mysqli connector. The response of the server in the case of an empty list should be different. Maybe the check if the result is 0 does not work. It should give back the constant for an empty list, if that is not the case the app assumes there is a list to work with. Jklmnn and beli3er are in charge of the php stuff and I bet they would love your support.

**Comment by jklmnn** [comment]
This has currently nothing to do with the mysql connector. Version 1.1 expects error codes that are currently not implemented in 0.3. You can either use app version 1.0 or use the experimental branch of the backend.
I just have looked through the code of the sqlite backend and noticed that the wrong code is given back also (independent from this issue). I'll fix this.
The experimental branch with sqlite returns for a non empty list: `{"type":1000,"items":[{"item":"item2","count":2}]}`. That's correct. But an empty list gives `{"type":1000,"items":[]}` which should be type 1001 and no items object at all.
I recommend using 1.0 since I had some issues with 1.1 crashing on a non empty list return.

**Comment by J-8** [comment]
This issue has probably been resolved now. If not, please reopen after a fresh install.
