### ISSUE TITLE
Untrusted/Self-signed certificates

### ISSUE THREAD

**Issue by AB933** [GroundApps/ShoppingList#51]
Very nice project.  Thank you.

I am stuck using a self-signed certificate because I use a home server.  Can you please give the option to accept a self-signed certificate?  It works if I install the certificate to the device but that is not an option in some cases.

Thank you!

**Comment by J-8** [comment]
Hey! Thanks for your feedback.
I have been planning on implementing that, but because I have had some issues with a previous project I always postponed it...
I am hoping for [letsencrypt.org](https://letsencrypt.org) to start handing out certificates soon, so the implementation would be unnecessary and time-consuming.
Maybe you could sign up for their beta test and see if that works out for you in the meanwhile?

**Comment by AB933** [comment]
I know about Let's Encrypt and I am excited about it.  Unfortunately, they do not support IIS at this time and I use IIS on Windows.  You will be happy to know that the Shopping List backend works perfectly on IIS so far.

**Comment by J-8** [comment]
Oh, I did not know that. Well then I'll get to it;)

**Comment by J-8** [comment]
I have experimented a bit, however, I have run into the same problems I have had last time. The user interaction is not very good. I am using MemorizingTrustManager, for which I cannot find a reliable documentation.

Please check out the app and tell me if it works and what you notice.
[Download Link](https://janb.org/index.php/s/WtyOwrNQqpBia5c)

**Comment by AB933** [comment]
It seems to work fine.  It asked me to accept the certificate and it did and then I was able to connect.  I had to exit the app and restart it to get it to connect..  As far as I am concerned, it's perfect.

Thank you!

**Comment by J-8** [comment]
Glad to hear that:)
It has some issues though. If you hit cancel it will keep trying to connect.
Oh and I can always recommend SpaceSSL, they have certificates for 9€ a year and they work perfectly fine for me.
