### ISSUE TITLE
Are favourites local ?

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#56]
I have been using ShoppingList on my phone for a while now and adding favourite items. Cool!
I recently installed it to our other devices , but when I go to add a favourite item on these new devices it shows 'You have no favourites yet - add some!'
Are the favourites only stored locally on each device ?
Could these favourite items also be sync'ed and stored on the server ?
Thanks.

**Comment by J-8** [comment]
Hey. Thanks for your feedback!
Hm, that is intentional. Personally, my girlfriend and I have different things we most likely add, so I never really thought about it.
It is possible, no question. But would probably require restructuring and adding something like different users, because I would not want to see the favorites of everybody.
I will think of a more elegant solution, which should ideally be easy to implement.

**Comment by ghost** [comment]
For now I am clicking on Favourites I have already added to the list and then edit and clicking Favourite , this creates it on the new device.
